<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <Authors>Michael Zillgith</Authors>
    <Company>MZ Automation</Company>
    <PackageId>lib60870</PackageId>
    <Version>2.3.0</Version>
    <RootNamespace>lib60870</RootNamespace>
    <AssemblyName>lib60870</AssemblyName>
    <ReleaseVersion>2.3.0</ReleaseVersion>
    <TargetFramework>net7.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <PackageIcon>icon.png</PackageIcon>
    <Description>
		lib60870.NET library for IEC 60870-5 based protocols in C#
		The current implementation contains code for the IEC 60870-5-101/104 protocols only.
	</Description>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageOutputPath>nupkg</PackageOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\lib60870\ASDUQueue.cs" />
    <Compile Include="..\lib60870\CS101\ASDU.cs" />
    <Compile Include="..\lib60870\CS101\ApplicationLayerParameters.cs" />
    <Compile Include="..\lib60870\CS101\BinaryCounterReading.cs" />
    <Compile Include="..\lib60870\CS101\Bitstring32.cs" />
    <Compile Include="..\lib60870\CS101\CauseOfTransmission.cs" />
    <Compile Include="..\lib60870\CS101\CS101Master.cs" />
    <Compile Include="..\lib60870\CS101\CS101Slave.cs" />
    <Compile Include="..\lib60870\CS101\DoublePointInformation.cs" />
    <Compile Include="..\lib60870\CS101\EndOfInitialization.cs" />
    <Compile Include="..\lib60870\CS101\EventOfProtectionEquipment.cs" />
    <Compile Include="..\lib60870\CS101\FileObjects.cs" />
    <Compile Include="..\lib60870\CS101\FileServices.cs" />
    <Compile Include="..\lib60870\CS101\InformationObject.cs" />
    <Compile Include="..\lib60870\CS101\IntegratedTotals.cs" />
    <Compile Include="..\lib60870\CS101\Master.cs" />
    <Compile Include="..\lib60870\CS101\MeasuredValueNormalized.cs" />
    <Compile Include="..\lib60870\CS101\MeasuredValueScaled.cs" />
    <Compile Include="..\lib60870\CS101\MeasuredValueShort.cs" />
    <Compile Include="..\lib60870\CS101\OutputCircuitInfo.cs" />
    <Compile Include="..\lib60870\CS101\PackedOutputCircuitInfo.cs" />
    <Compile Include="..\lib60870\CS101\PackedStartEventsOfProtectionEquipment.cs" />
    <Compile Include="..\lib60870\CS101\ParameterMeasuredValues.cs" />
    <Compile Include="..\lib60870\CS101\QualityDescriptor.cs" />
    <Compile Include="..\lib60870\CS101\QualityDescriptorP.cs" />
    <Compile Include="..\lib60870\CS101\ScaledValue.cs" />
    <Compile Include="..\lib60870\CS101\SetpointCommandQualifier.cs" />
    <Compile Include="..\lib60870\CS101\SetpointCommands.cs" />
    <Compile Include="..\lib60870\CS101\SingleCommand.cs" />
    <Compile Include="..\lib60870\CS101\SingleCommandQualifier.cs" />
    <Compile Include="..\lib60870\CS101\SingleEvent.cs" />
    <Compile Include="..\lib60870\CS101\SinglePointInformation.cs" />
    <Compile Include="..\lib60870\CS101\Slave.cs" />
    <Compile Include="..\lib60870\CS101\StartEvent.cs" />
    <Compile Include="..\lib60870\CS101\StatusAndStatusChangeDetection.cs" />
    <Compile Include="..\lib60870\CS101\StepPositionInformation.cs" />
    <Compile Include="..\lib60870\CS101\SystemInformationCommands.cs" />
    <Compile Include="..\lib60870\CS101\TypeID.cs" />
    <Compile Include="..\lib60870\Properties\AssemblyInfo.cs" />
    <Compile Include="..\lib60870\CP56Time2a.cs" />
    <Compile Include="..\lib60870\SystemUtils.cs" />
    <Compile Include="..\lib60870\CP24Time2a.cs" />
    <Compile Include="..\lib60870\CP16Time2a.cs" />
    <Compile Include="..\lib60870\Frame.cs" />
    <Compile Include="..\lib60870\LibraryCommon.cs" />
    <Compile Include="..\lib60870\CP32Time2a.cs" />
    <Compile Include="..\lib60870\ASDUParsingException.cs" />
    <Compile Include="..\lib60870\CS104\APCIParameters.cs" />
    <Compile Include="..\lib60870\CS104\Connection.cs" />
    <Compile Include="..\lib60870\CS104\Server.cs" />
    <Compile Include="..\lib60870\CS104\TlsSecurityInformation.cs" />
    <Compile Include="..\lib60870\LinkLayer\LinkLayer.cs" />
    <Compile Include="..\lib60870\LinkLayer\PrimaryLinkLayer.cs" />
    <Compile Include="..\lib60870\LinkLayer\SecondaryLinkLayer.cs" />
    <Compile Include="..\lib60870\LinkLayer\SerialTransceiverFT12.cs" />
    <Compile Include="..\lib60870\ConnectionException.cs" />
    <Compile Include="..\lib60870\BufferFrame.cs" />
    <Compile Include="..\lib60870\LinkLayer\PrimaryLinkLayerBalanced.cs" />
    <Compile Include="..\lib60870\LinkLayer\PrimaryLinkLayerUnbalanced.cs" />
    <Compile Include="..\lib60870\LinkLayer\SecondaryLinkLayerBalanced.cs" />
    <Compile Include="..\lib60870\LinkLayer\SecondaryLinkLayerUnbalanced.cs" />
    <Compile Include="..\lib60870\LinkLayer\TcpServerVirtualSerialPort.cs" />
    <Compile Include="..\lib60870\LinkLayer\TcpClientVirtualSerialPort.cs" />
    <Compile Include="..\lib60870\CS104\ClientConnection.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="7.0.0" />
    <None Include="..\lib60870\images\icon.png" Pack="true" PackagePath="\" />
    <None Include="..\lib60870\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="nupkg\" />
  </ItemGroup>
</Project>